---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  test-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Run build
          command: yarn build
  check-prettier:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Run Prettier over all files
          command: yarn prettier-check
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Lint Sass and JS
          command: yarn test
workflows:
  version: 2
  build:
    jobs:
      - test-build
      - check-prettier
      - test
